import type {Metadata} from "next";
import PromptOptimizerDemo from "./PromptOptimizerDemo";
import "./prompt-optimizer.css";

export const metadata:Metadata={
 title:"Prompt Optimizer Indonesia: Ubah Prompt Sederhana Jadi Lebih Terstruktur",
 description:"Demo gratis AIUpdateId untuk mengubah instruksi sederhana menjadi prompt yang lebih jelas, terstruktur, dan siap diuji di AI pilihan Anda.",
 alternates:{canonical:"/tools/prompt-optimizer"},
 openGraph:{title:"Prompt Optimizer Indonesia — Demo Gratis AIUpdateId",description:"Masukkan instruksi sederhana, lengkapi konteks penting, lalu dapatkan prompt profesional yang siap diuji.",type:"website",url:"/tools/prompt-optimizer"}
};
export default function Page(){return <main className="pcPage"><section className="container pcHero"><div className="pcBadge">AIUPDATEID LABS · GRATIS</div><h1>Prompt kamu tidak harus sempurna.<br/><em>Sistemnya yang harus membantu.</em></h1><p>Masukkan instruksi sederhana. Demo ini membantu menyusun tujuan, audiens, konteks, format, dan batasan menjadi prompt yang lebih siap digunakan—tanpa meminta kamu memahami teknik prompting terlebih dahulu.</p><div className="pcTrust"><span>✓ Tanpa login</span><span>✓ Tanpa API key</span><span>✓ Tidak ada paket berbayar</span></div></section><section className="container pcDemo"><PromptOptimizerDemo/></section><section className="container pcExplain"><div><small>KENAPA KAMI MEMBUATNYA</small><h2>Prompt yang buruk sering kali bukan masalah kata-kata.</h2><p>Masalahnya adalah informasi penting belum diberikan: siapa audiensnya, apa tujuan akhirnya, konteks apa yang harus dipahami AI, dan batasan apa yang tidak boleh dilanggar. Demo ini berfokus pada struktur tersebut.</p></div><div className="pcExplainCards"><article><b>01</b><h3>Deteksi yang kurang</h3><p>Sistem menandai konteks penting yang belum tersedia, bukan langsung menebaknya.</p></article><article><b>02</b><h3>Susun instruksi</h3><p>Input sederhana diubah menjadi brief yang lebih eksplisit dan mudah diikuti model AI.</p></article><article><b>03</b><h3>Tetap kritis</h3><p>Prompt memasukkan batasan agar model tidak didorong mengarang fakta hanya demi menyelesaikan tugas.</p></article></div><div className="pcLabNote"><strong>Status: eksperimen publik.</strong> AIUpdateId belum mengklaim prompt hasil demo selalu lebih baik. Kami justru ingin mengujinya melalui penggunaan nyata sebelum membangun versi yang lebih kompleks.</div></section></main>}
