"use client";
import Link from "next/link";
import {useMemo,useState} from "react";
import {ArrowUpRight,BadgeCheck,Search,Sparkles,Star,SlidersHorizontal} from "lucide-react";
import BrandLogo from "@/components/BrandLogo";
import type {AITool} from "@/lib/tool-types";
function logo(t:AITool){return <BrandLogo provider={t.provider} name={t.name} logoUrl={t.logo_url}/>}
export default function ToolsDirectoryClient({tools}:{tools:AITool[]}){
 const[q,setQ]=useState("");const[category,setCategory]=useState("Semua");const[freeOnly,setFreeOnly]=useState(false);const[sort,setSort]=useState("featured");
 const categories=useMemo(()=>["Semua",...Array.from(new Set(tools.map(x=>x.category).filter(Boolean) as string[])).sort()],[tools]);
 const filtered=useMemo(()=>{const query=q.trim().toLowerCase();const rows=tools.filter(t=>{const h=[t.name,t.provider,t.short_description,t.category,...(t.tags||[]),...(t.best_for||[])].filter(Boolean).join(" ").toLowerCase();return(!query||h.includes(query))&&(category==="Semua"||t.category===category)&&(!freeOnly||t.has_free_plan)});return [...rows].sort((a,b)=>sort==="rating"?Number(b.rating||0)-Number(a.rating||0):sort==="name"?a.name.localeCompare(b.name):Number(Boolean(b.featured))-Number(Boolean(a.featured))||Number(b.rating||0)-Number(a.rating||0))},[tools,q,category,freeOnly,sort]);
 const featured=tools.filter(x=>x.featured).slice(0,3);
 return <main className="page toolsPage"><section className="toolsHero"><div className="container toolsHeroGrid"><div><span className="toolsEyebrow"><Sparkles size={16}/> AI TOOLS DIRECTORY</span><h1>Temukan AI yang tepat untuk pekerjaan Anda.</h1><p>Direktori AIUpdateId membantu membandingkan fungsi, harga, platform, kelebihan, kekurangan, dan kecocokan setiap tool—tanpa harus membuka puluhan tab.</p><div className="toolsHeroStats"><div><b>{tools.length}</b><span>Tools terverifikasi</span></div><div><b>{categories.length-1}</b><span>Kategori</span></div><div><b>{tools.filter(x=>x.has_free_plan).length}</b><span>Punya akses gratis</span></div></div></div><div className="toolsHeroPanel"><span>MULAI DARI KEBUTUHAN</span><h2>Jangan cari AI “terbaik”. Cari AI yang paling cocok.</h2><p>Gunakan filter berdasarkan kategori dan akses gratis.</p></div></div></section>
 {featured.length>0&&<section className="container toolsFeatured"><div className="toolsSectionHeading"><div><small>PILIHAN EDITOR</small><h2>Tools unggulan</h2></div></div><div className="featuredToolGrid">{featured.map(t=><Link href={`/tools/${t.slug}`} className="featuredToolCard" key={t.id}><div className="directoryLogo">{logo(t)}</div><div><small>{t.category||"AI Tool"}</small><h3>{t.name}</h3><p>{t.short_description}</p><span className="toolCardRating"><Star size={15}/>{Number(t.rating||0).toFixed(1)}</span></div><ArrowUpRight size={20}/></Link>)}</div></section>}
 <section className="container toolsDirectorySection"><div className="toolsSectionHeading"><div><small>DIREKTORI</small><h2>Jelajahi semua AI Tools</h2></div><span>{filtered.length} hasil</span></div><div className="toolsFilters"><label className="toolsSearch"><Search size={19}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Cari ChatGPT, coding, riset, gambar..."/></label><label className="toolsSelect"><SlidersHorizontal size={17}/><select value={sort} onChange={e=>setSort(e.target.value)}><option value="featured">Rekomendasi</option><option value="rating">Rating tertinggi</option><option value="name">Nama A–Z</option></select></label><label className="freeFilter"><input type="checkbox" checked={freeOnly} onChange={e=>setFreeOnly(e.target.checked)}/><span>Gratis tersedia</span></label></div><div className="toolCategoryPills">{categories.map(c=><button key={c} className={category===c?"active":""} onClick={()=>setCategory(c)}>{c}</button>)}</div>
 {filtered.length?<div className="toolDirectoryGrid">{filtered.map(t=><article className="toolDirectoryCard" key={t.id}><div className="toolCardTop"><div className="directoryLogo">{logo(t)}</div><div className="toolBadges">{t.featured&&<span className="editorBadge"><BadgeCheck size={13}/> Pilihan Editor</span>}{t.has_free_plan&&<span className="freeBadge">Gratis</span>}</div></div><div className="toolCardMeta"><span>{t.category||"AI Tool"}</span>{t.provider&&<span>• {t.provider}</span>}</div><h2><Link href={`/tools/${t.slug}`}>{t.name}</Link></h2><p>{t.short_description||"Informasi tool sedang dilengkapi."}</p>{t.best_for?.length?<div className="toolBestFor">{t.best_for.slice(0,3).map(v=><span key={v}>{v}</span>)}</div>:null}<div className="toolCardFooter"><span className="toolCardRating"><Star size={16}/>{Number(t.rating||0).toFixed(1)}<small>/10</small></span><Link href={`/tools/${t.slug}`}>Lihat detail <ArrowUpRight size={16}/></Link></div></article>)}</div>:<div className="empty toolsEmpty">Tidak ada tool yang cocok dengan filter ini.</div>}</section></main>
}
