-- Starter data AI Tools Directory V1
-- Semua status draft. Review fakta/harga sebelum publish.

insert into public.ai_tools (name,slug,provider,category,short_description,official_url,pricing,has_free_plan,platforms,best_for,status,featured,last_reviewed_at) values ('ChatGPT','chatgpt','OpenAI','Chatbot','Asisten AI serbaguna untuk menulis, belajar, riset, coding, analisis, dan produktivitas.','https://chatgpt.com/','Gratis & opsi berbayar',true,ARRAY['Web','iOS','Android','Desktop']::text[],ARRAY['Menulis','Belajar','Coding','Produktivitas']::text[],'draft',false,current_date) on conflict (slug) do update set provider=excluded.provider,category=excluded.category,short_description=excluded.short_description,official_url=excluded.official_url,pricing=excluded.pricing,platforms=excluded.platforms,best_for=excluded.best_for,updated_at=now();

insert into public.ai_tools (name,slug,provider,category,short_description,official_url,pricing,has_free_plan,platforms,best_for,status,featured,last_reviewed_at) values ('Gemini','gemini','Google','Chatbot','Asisten AI Google yang terintegrasi erat dengan ekosistem Google dan mendukung berbagai kebutuhan produktivitas.','https://gemini.google.com/','Gratis & opsi berbayar',true,ARRAY['Web','Android','iOS']::text[],ARRAY['Google Workspace','Belajar','Riset']::text[],'draft',false,current_date) on conflict (slug) do update set provider=excluded.provider,category=excluded.category,short_description=excluded.short_description,official_url=excluded.official_url,pricing=excluded.pricing,platforms=excluded.platforms,best_for=excluded.best_for,updated_at=now();

insert into public.ai_tools (name,slug,provider,category,short_description,official_url,pricing,has_free_plan,platforms,best_for,status,featured,last_reviewed_at) values ('Claude','claude','Anthropic','Chatbot','Asisten AI untuk membaca, menulis, berdiskusi, dan bekerja dengan konteks atau dokumen panjang.','https://claude.ai/','Gratis & opsi berbayar',true,ARRAY['Web','iOS','Android','Desktop']::text[],ARRAY['Menulis','Dokumen panjang','Analisis']::text[],'draft',false,current_date) on conflict (slug) do update set provider=excluded.provider,category=excluded.category,short_description=excluded.short_description,official_url=excluded.official_url,pricing=excluded.pricing,platforms=excluded.platforms,best_for=excluded.best_for,updated_at=now();

insert into public.ai_tools (name,slug,provider,category,short_description,official_url,pricing,has_free_plan,platforms,best_for,status,featured,last_reviewed_at) values ('Perplexity','perplexity','Perplexity','Research','Mesin pencarian berbasis AI yang membantu menemukan informasi web dan rujukan menuju sumber.','https://www.perplexity.ai/','Gratis & opsi berbayar',true,ARRAY['Web','iOS','Android']::text[],ARRAY['Riset','Pencarian sumber','Belajar']::text[],'draft',false,current_date) on conflict (slug) do update set provider=excluded.provider,category=excluded.category,short_description=excluded.short_description,official_url=excluded.official_url,pricing=excluded.pricing,platforms=excluded.platforms,best_for=excluded.best_for,updated_at=now();

insert into public.ai_tools (name,slug,provider,category,short_description,official_url,pricing,has_free_plan,platforms,best_for,status,featured,last_reviewed_at) values ('NotebookLM','notebooklm','Google','Education','Asisten belajar dan riset berbasis sumber seperti dokumen, PDF, dan materi pengguna.','https://notebooklm.google.com/','Gratis & opsi berbayar',true,ARRAY['Web']::text[],ARRAY['Mahasiswa','Riset dokumen','Belajar']::text[],'draft',false,current_date) on conflict (slug) do update set provider=excluded.provider,category=excluded.category,short_description=excluded.short_description,official_url=excluded.official_url,pricing=excluded.pricing,platforms=excluded.platforms,best_for=excluded.best_for,updated_at=now();

insert into public.ai_tools (name,slug,provider,category,short_description,official_url,pricing,has_free_plan,platforms,best_for,status,featured,last_reviewed_at) values ('Microsoft Copilot','microsoft-copilot','Microsoft','Productivity','Asisten AI Microsoft untuk pencarian, produktivitas, penulisan, dan ekosistem Microsoft.','https://copilot.microsoft.com/','Gratis & opsi berbayar',true,ARRAY['Web','Windows','iOS','Android']::text[],ARRAY['Produktivitas','Microsoft ecosystem']::text[],'draft',false,current_date) on conflict (slug) do update set provider=excluded.provider,category=excluded.category,short_description=excluded.short_description,official_url=excluded.official_url,pricing=excluded.pricing,platforms=excluded.platforms,best_for=excluded.best_for,updated_at=now();

insert into public.ai_tools (name,slug,provider,category,short_description,official_url,pricing,has_free_plan,platforms,best_for,status,featured,last_reviewed_at) values ('GitHub Copilot','github-copilot','GitHub','Coding','Asisten coding AI untuk membantu menulis, memahami, dan memperbaiki kode dalam workflow developer.','https://github.com/features/copilot','Gratis & opsi berbayar',true,ARRAY['Web','IDE']::text[],ARRAY['Programmer','Software development','Coding']::text[],'draft',false,current_date) on conflict (slug) do update set provider=excluded.provider,category=excluded.category,short_description=excluded.short_description,official_url=excluded.official_url,pricing=excluded.pricing,platforms=excluded.platforms,best_for=excluded.best_for,updated_at=now();

insert into public.ai_tools (name,slug,provider,category,short_description,official_url,pricing,has_free_plan,platforms,best_for,status,featured,last_reviewed_at) values ('DeepSeek','deepseek','DeepSeek','Chatbot','Asisten dan model AI untuk percakapan, reasoning, pekerjaan teknis, dan coding.','https://www.deepseek.com/','Gratis / API berbayar',true,ARRAY['Web','App','API']::text[],ARRAY['Coding','Reasoning','Eksperimen AI']::text[],'draft',false,current_date) on conflict (slug) do update set provider=excluded.provider,category=excluded.category,short_description=excluded.short_description,official_url=excluded.official_url,pricing=excluded.pricing,platforms=excluded.platforms,best_for=excluded.best_for,updated_at=now();

insert into public.ai_tools (name,slug,provider,category,short_description,official_url,pricing,has_free_plan,platforms,best_for,status,featured,last_reviewed_at) values ('Grok','grok','xAI','Chatbot','Asisten AI dari xAI untuk percakapan, informasi, penulisan, analisis, dan penggunaan umum.','https://grok.com/','Gratis terbatas & opsi berbayar',true,ARRAY['Web','iOS','Android']::text[],ARRAY['Percakapan','Informasi','Produktivitas']::text[],'draft',false,current_date) on conflict (slug) do update set provider=excluded.provider,category=excluded.category,short_description=excluded.short_description,official_url=excluded.official_url,pricing=excluded.pricing,platforms=excluded.platforms,best_for=excluded.best_for,updated_at=now();

insert into public.ai_tools (name,slug,provider,category,short_description,official_url,pricing,has_free_plan,platforms,best_for,status,featured,last_reviewed_at) values ('Canva AI','canva-ai','Canva','Design','Fitur AI di Canva untuk desain, konten visual, presentasi, dan workflow kreatif.','https://www.canva.com/ai-assistant/','Gratis terbatas & opsi berbayar',true,ARRAY['Web','Desktop','iOS','Android']::text[],ARRAY['Desain','Presentasi','Konten sosial']::text[],'draft',false,current_date) on conflict (slug) do update set provider=excluded.provider,category=excluded.category,short_description=excluded.short_description,official_url=excluded.official_url,pricing=excluded.pricing,platforms=excluded.platforms,best_for=excluded.best_for,updated_at=now();
