"use client";
import {useEffect,useState} from "react";
import {useRouter} from "next/navigation";
import {supabase} from "@/lib/supabase";
import {Edit3,Plus,Trash2} from "lucide-react";

type Field={key:string;label:string;type?:"text"|"textarea"|"number"|"checkbox"|"select";options?:string[]};
export default function SimpleCrud({table,title,fields,defaults}:{table:string;title:string;fields:Field[];defaults:Record<string,any>}){
 const router=useRouter();const[items,setItems]=useState<any[]>([]);const[form,setForm]=useState<any>(defaults);const[editing,setEditing]=useState<string|null>(null);const[error,setError]=useState("");
 const load=async()=>{const{data,error}=await supabase.from(table).select("*").order("created_at",{ascending:false});if(error)setError(error.message);else setItems(data||[])};
 useEffect(()=>{supabase.auth.getSession().then(({data})=>{if(!data.session)router.replace("/admin");else load()})},[router]);
 const save=async(e:React.FormEvent)=>{e.preventDefault();setError("");const payload={...form,updated_at:new Date().toISOString()};const r=editing?await supabase.from(table).update(payload).eq("id",editing):await supabase.from(table).insert(payload);if(r.error)setError(r.error.message);else{setForm(defaults);setEditing(null);load()}};
 const edit=(x:any)=>{setEditing(x.id);setForm(fields.reduce((a,f)=>({...a,[f.key]:x[f.key]??defaults[f.key]}),{}));window.scrollTo({top:0,behavior:"smooth"})};
 const del=async(id:string)=>{if(!confirm("Hapus data ini?"))return;await supabase.from(table).delete().eq("id",id);load()};
 return <main className="adminPage"><div className="adminShell"><aside><b>AIUpdateId Admin</b><a href="/admin/dashboard">Dashboard</a><a href="/admin/artikel/baru">Artikel</a><a href="/admin/media">Media</a><a href="/admin/tools">AI Tools</a><a href="/admin/models">AI Models</a><a href="/admin/glossary">Glossary</a><a href="/admin/comparisons">Comparison</a></aside><section className="adminContent"><div className="adminTop"><div><small>V9 DATABASE</small><h1>{title}</h1></div></div>{error&&<div className="errorBox">{error}</div>}<form className="v9CrudForm" onSubmit={save}>{fields.map(f=><label key={f.key}>{f.label}{f.type==="textarea"?<textarea rows={4} value={form[f.key]??""} onChange={e=>setForm({...form,[f.key]:e.target.value})}/>:f.type==="checkbox"?<input type="checkbox" checked={!!form[f.key]} onChange={e=>setForm({...form,[f.key]:e.target.checked})}/>:f.type==="select"?<select value={form[f.key]??""} onChange={e=>setForm({...form,[f.key]:e.target.value})}>{(f.options||[]).map(o=><option key={o}>{o}</option>)}</select>:<input type={f.type==="number"?"number":"text"} step="0.1" value={form[f.key]??""} onChange={e=>setForm({...form,[f.key]:f.type==="number"?Number(e.target.value):e.target.value})}/>}</label>)}<button className="primary"><Plus size={17}/>{editing?"Simpan Perubahan":"Tambah Data"}</button></form><div className="v9CrudList">{items.map(x=><article key={x.id}><div><b>{x.name||x.term||x.title}</b><span>{x.status||x.category||x.provider||""}</span></div><div><button onClick={()=>edit(x)}><Edit3 size={16}/></button><button onClick={()=>del(x.id)}><Trash2 size={16}/></button></div></article>)}</div></section></div></main>
}
