export type Article = {
  id: string;
  title: string;
  slug: string;
  excerpt: string | null;
  content: string | null;
  category: string | null;
  cover_image: string | null;
  status: string | null;
  featured: boolean | null;
  read_time: string | null;
  created_at: string;
  updated_at: string;
  published_at: string | null;
  seo_title: string | null;
  meta_description: string | null;
  tags: string[] | null;
  focus_keyword: string | null;
  canonical_url: string | null;
  og_title: string | null;
  og_description: string | null;
  alt_text: string | null;
  image_caption: string | null;
  image_source: string | null;
  faq: { question: string; answer: string }[] | null;
  call_to_action: string | null;
  breaking: boolean | null;
  scheduled_at: string | null;
  no_index: boolean | null;
  editor_pick: boolean | null;
  view_count: number | null;
};
